name: Build1_test
trigger:
  - main
resources:
  repositories:
    - repository: AutomatedTestsRepo
      type : github
      endpoint: connection
      name: MyGitHubRepo/AutomatedTests
…
  steps:
    - checkout: self
    - checkout: AutomatedTestsRepo
      path: AutomatedTests
      clean: true

